// dropAndSeed.js
// Run from your backend folder: node dropAndSeed.js

import mongoose from "mongoose";

const MONGO_URI = "mongodb://localhost:27017/Curely";

const doctorSchema = new mongoose.Schema({
  name: String,
  email: String,
  password: String,
  image: String,
  speciality: String,
  degree: String,
  experience: String,
  about: String,
  available: Boolean,
  fees: Number,
  address: Object,
  date: Number,
  slots_booked: Object,
});

const Doctor = mongoose.models.doctor || mongoose.model("doctor", doctorSchema);

// All images from Unsplash — professional doctor/medical attire
const doctors = [
  {
    name: "Dr. Arjun Sharma",
    email: "arjun.sharma@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&h=300&fit=crop&crop=face",
    speciality: "General physician",
    degree: "MBBS",
    experience: "4 Years",
    about: "Dr. Sharma has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 500,
    address: { line1: "12, Rajouri Garden", line2: "New Delhi, Delhi" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Priya Mehta",
    email: "priya.mehta@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&h=300&fit=crop&crop=face",
    speciality: "Gynecologist",
    degree: "MBBS, MD",
    experience: "3 Years",
    about: "Dr. Mehta has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 600,
    address: { line1: "45, Banjara Hills", line2: "Hyderabad, Telangana" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Sneha Iyer",
    email: "sneha.iyer@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=300&h=300&fit=crop&crop=face",
    speciality: "Dermatologist",
    degree: "MBBS, DVD",
    experience: "1 Years",
    about: "Dr. Iyer has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 300,
    address: { line1: "8, Koregaon Park", line2: "Pune, Maharashtra" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Rohan Verma",
    email: "rohan.verma@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&h=300&fit=crop&crop=face",
    speciality: "Pediatricians",
    degree: "MBBS, DCH",
    experience: "2 Years",
    about: "Dr. Verma has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 400,
    address: { line1: "22, Salt Lake", line2: "Kolkata, West Bengal" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Kavitha Nair",
    email: "kavitha.nair@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=300&h=300&fit=crop&crop=face",
    speciality: "Neurologist",
    degree: "MBBS, DM",
    experience: "4 Years",
    about: "Dr. Nair has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 700,
    address: { line1: "3, MG Road", line2: "Bangalore, Karnataka" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Vikram Patel",
    email: "vikram.patel@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&h=300&fit=crop&crop=face",
    speciality: "Neurologist",
    degree: "MBBS, MD",
    experience: "4 Years",
    about: "Dr. Patel has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 700,
    address: { line1: "17, CG Road", line2: "Ahmedabad, Gujarat" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Amit Khanna",
    email: "amit.khanna@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=300&h=300&fit=crop&crop=face",
    speciality: "General physician",
    degree: "MBBS",
    experience: "5 Years",
    about: "Dr. Khanna has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 500,
    address: { line1: "9, Connaught Place", line2: "New Delhi, Delhi" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Ananya Reddy",
    email: "ananya.reddy@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=300&h=300&fit=crop&crop=face",
    speciality: "Gynecologist",
    degree: "MBBS, MS",
    experience: "3 Years",
    about: "Dr. Reddy has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 600,
    address: { line1: "34, Jubilee Hills", line2: "Hyderabad, Telangana" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Neha Joshi",
    email: "neha.joshi@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1623854767648-e7bb8009f0db?w=300&h=300&fit=crop&crop=face",
    speciality: "Dermatologist",
    degree: "MBBS, MD",
    experience: "2 Years",
    about: "Dr. Joshi has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 350,
    address: { line1: "56, FC Road", line2: "Pune, Maharashtra" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Rahul Gupta",
    email: "rahul.gupta@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1618498082410-b4aa22193b38?w=300&h=300&fit=crop&crop=face",
    speciality: "Pediatricians",
    degree: "MBBS, MD",
    experience: "3 Years",
    about: "Dr. Gupta has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 450,
    address: { line1: "11, Andheri West", line2: "Mumbai, Maharashtra" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Meera Krishnan",
    email: "meera.krishnan@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&h=300&fit=crop&crop=face",
    speciality: "Gastroenterologist",
    degree: "MBBS, DM",
    experience: "6 Years",
    about: "Dr. Krishnan has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 800,
    address: { line1: "2, Anna Nagar", line2: "Chennai, Tamil Nadu" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Suresh Bhat",
    email: "suresh.bhat@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=300&h=300&fit=crop&crop=face",
    speciality: "Neurologist",
    degree: "MBBS, DM",
    experience: "7 Years",
    about: "Dr. Bhat has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 900,
    address: { line1: "5, Malleshwaram", line2: "Bangalore, Karnataka" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Pooja Singh",
    email: "pooja.singh@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=300&h=300&fit=crop&crop=face",
    speciality: "General physician",
    degree: "MBBS",
    experience: "4 Years",
    about: "Dr. Singh has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 500,
    address: { line1: "78, Hazratganj", line2: "Lucknow, Uttar Pradesh" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Kiran Desai",
    email: "kiran.desai@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1591604021695-0c69b7c05981?w=300&h=300&fit=crop&crop=face",
    speciality: "Gynecologist",
    degree: "MBBS, MS",
    experience: "5 Years",
    about: "Dr. Desai has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 650,
    address: { line1: "33, Navrangpura", line2: "Ahmedabad, Gujarat" },
    date: Date.now(),
    slots_booked: {},
  },
  {
    name: "Dr. Rajesh Pillai",
    email: "rajesh.pillai@curely.com",
    password: "doctor123",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&h=300&fit=crop&crop=face&sig=2",
    speciality: "Dermatologist",
    degree: "MBBS, DVD",
    experience: "3 Years",
    about: "Dr. Pillai has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    available: true,
    fees: 400,
    address: { line1: "14, Vazhuthacaud", line2: "Thiruvananthapuram, Kerala" },
    date: Date.now(),
    slots_booked: {},
  },
];

async function dropAndSeed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected to MongoDB");

    await mongoose.connection.collection("doctors").drop().catch(() => {
      console.log("ℹ️  No existing collection to drop, continuing...");
    });
    console.log("🗑️  Dropped old doctors collection");

    await Doctor.insertMany(doctors);
    console.log(`✅ Successfully seeded ${doctors.length} doctors with professional photos!`);
    console.log("   Restart your backend and refresh the frontend.");
    process.exit(0);
  } catch (err) {
    console.error("❌ Failed:", err.message);
    process.exit(1);
  }
}

dropAndSeed();