import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config();

const doctors = [
  {
    name: "Dr. Rahul Sharma",
    email: "rahul@gmail.com",
    password: "doctor123",
    speciality: "General physician",
    degree: "MBBS",
    experience: "5 Years",
    about: "Dr. Rahul is a trusted general physician with 5 years of experience in treating common illnesses.",
    available: true,
    fees: 500,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    address: { line1: "17th Cross, Richmond", line2: "Ring Road, Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Vikram Singh",
    email: "vikram@gmail.com",
    password: "doctor123",
    speciality: "General physician",
    degree: "MBBS, MD",
    experience: "8 Years",
    about: "Dr. Vikram is an experienced general physician known for his patient friendly approach.",
    available: true,
    fees: 600,
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    address: { line1: "8th Road, Juhu", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Priya Patel",
    email: "priya@gmail.com",
    password: "doctor123",
    speciality: "Gynecologist",
    degree: "MBBS, MD",
    experience: "8 Years",
    about: "Dr. Priya specializes in women's health and has helped thousands of patients.",
    available: true,
    fees: 700,
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    address: { line1: "27th Street, Bandra", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Ananya Gupta",
    email: "ananya@gmail.com",
    password: "doctor123",
    speciality: "Gynecologist",
    degree: "MBBS, DGO",
    experience: "10 Years",
    about: "Dr. Ananya is a senior gynecologist with expertise in maternal and reproductive health.",
    available: true,
    fees: 800,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    address: { line1: "33rd Street, Colaba", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Arjun Mehta",
    email: "arjun@gmail.com",
    password: "doctor123",
    speciality: "Dermatologist",
    degree: "MBBS, MD Dermatology",
    experience: "6 Years",
    about: "Dr. Arjun is an expert in skin disorders and cosmetic dermatology.",
    available: true,
    fees: 600,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    address: { line1: "45th Avenue, Andheri", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Suresh Verma",
    email: "suresh@gmail.com",
    password: "doctor123",
    speciality: "Dermatologist",
    degree: "MBBS, MD Dermatology",
    experience: "9 Years",
    about: "Dr. Suresh specializes in skin care treatments and dermatological procedures.",
    available: true,
    fees: 700,
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    address: { line1: "3rd Street, Kandivali", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Sneha Reddy",
    email: "sneha@gmail.com",
    password: "doctor123",
    speciality: "Pediatricians",
    degree: "MBBS, MD Pediatrics",
    experience: "10 Years",
    about: "Dr. Sneha is a caring pediatrician dedicated to the health and wellbeing of children.",
    available: true,
    fees: 650,
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    address: { line1: "12th Lane, Powai", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Pooja Desai",
    email: "pooja@gmail.com",
    password: "doctor123",
    speciality: "Pediatricians",
    degree: "MBBS, DCH",
    experience: "7 Years",
    about: "Dr. Pooja is a friendly pediatrician who specializes in child growth and development.",
    available: true,
    fees: 600,
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    address: { line1: "18th Cross, Thane", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Rohan Joshi",
    email: "rohan@gmail.com",
    password: "doctor123",
    speciality: "Neurologist",
    degree: "MBBS, DM Neurology",
    experience: "12 Years",
    about: "Dr. Rohan is a leading neurologist specializing in brain and nervous system disorders.",
    available: true,
    fees: 1000,
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    address: { line1: "21st Cross, Dadar", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Kavita Nair",
    email: "kavita@gmail.com",
    password: "doctor123",
    speciality: "Neurologist",
    degree: "MBBS, DM Neurology",
    experience: "15 Years",
    about: "Dr. Kavita is a senior neurologist with expertise in treating complex neurological conditions.",
    available: true,
    fees: 1200,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    address: { line1: "5th Avenue, Worli", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Aditya Kumar",
    email: "aditya@gmail.com",
    password: "doctor123",
    speciality: "Gastroenterologist",
    degree: "MBBS, MD Gastroenterology",
    experience: "8 Years",
    about: "Dr. Aditya specializes in digestive system disorders and gastrointestinal health.",
    available: true,
    fees: 850,
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    address: { line1: "14th Road, Malad", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
  {
    name: "Dr. Meera Iyer",
    email: "meera@gmail.com",
    password: "doctor123",
    speciality: "Gastroenterologist",
    degree: "MBBS, MD Gastroenterology",
    experience: "11 Years",
    about: "Dr. Meera is an experienced gastroenterologist providing comprehensive digestive care.",
    available: true,
    fees: 900,
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    address: { line1: "9th Lane, Borivali", line2: "Mumbai" },
    date: 1627996800000,
    slots_booked: {},
  },
];

const seedDoctors = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      tls: true,
      tlsAllowInvalidCertificates: true,
    });
    console.log("Connected to MongoDB");
    const db = mongoose.connection.db;
    await db.collection("doctors").insertMany(doctors);
    console.log("✅ 12 Doctors inserted successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error:", error);
    process.exit(1);
  }
};

seedDoctors();